database:
  connection:
    host: "localhost"
    port: 27017
    username: ""  # Leave empty if no authentication is required
    password: ""  # Leave empty if no authentication is required
  settings:
    name: "mold_prevention"  # Your database name
    auth_source: "admin"